version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    # Allow both version and security updates
    allow:
      - dependency-type: "all"

  - package-ecosystem: "cargo"
    directory: "/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
