version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: tools-backend
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000,http://frontend:3000}
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - tools-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://backend:3001}
        - NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH:-}
        - BUILD_STATIC=${BUILD_STATIC:-false}
    container_name: tools-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    depends_on:
      - backend
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - tools-network

networks:
  tools-network:
    driver: bridge
