version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: tools-backend
    ports:
      - "3001:3001"
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    networks:
      - tools-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: tools-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - tools-network

networks:
  tools-network:
    driver: bridge
