name: CD - Build & Push Docker Images

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-and-push:
    name: Build and push multi-arch images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR (GITHUB_TOKEN or GHCR_PAT)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT || secrets.GITHUB_TOKEN }}

      - name: Build and push backend (multi-arch)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/backend.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/tools-backend:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/tools-backend:latest

      - name: Build and push frontend (multi-arch)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/frontend.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/tools-frontend:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/tools-frontend:latest

      - name: Install cosign
        run: |
          COSIGN_VERSION=2.12.0
          curl -sSL -o cosign "https://github.com/sigstore/cosign/releases/download/v${COSIGN_VERSION}/cosign-linux-amd64"
          chmod +x cosign
          sudo mv cosign /usr/local/bin/cosign

      - name: Sign backend image (keyless)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Signing backend images with cosign (keyless via OIDC)"
          cosign version || true
          cosign sign --keyless ghcr.io/${{ github.repository_owner }}/tools-backend:${{ github.ref_name }}
          cosign sign --keyless ghcr.io/${{ github.repository_owner }}/tools-backend:latest

      - name: Sign frontend image (keyless)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Signing frontend images with cosign (keyless via OIDC)"
          cosign sign --keyless ghcr.io/${{ github.repository_owner }}/tools-frontend:${{ github.ref_name }}
          cosign sign --keyless ghcr.io/${{ github.repository_owner }}/tools-frontend:latest
